### ISSUE TITLE
chrome禁用了第三方插件

### ISSUE THREAD

**Issue by ansongd** [Kumhy/360Exporter#1]
chrome禁用了第三方js插件了，请问这个js怎么加载呢，我试用用chrome store里面的插件加载js代码但是不会手动设置

**Comment by Kumhy** [comment]
开发者模式加载

**Comment by ansongd** [comment]
有几个错误导致不能自定义aria2地址
错误一（红叉-严重）：

> ixed Content: The page at 'https://c91.yunpan.360.cn/my/?sid=#%2F%E5%B8%B8%E7%94%A8%E7%B4%A0%E6%9D%90%2FEARTHRIVERlogo%2F' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://localhost:6800/jsonrpc'. This request has been blocked; this endpoint must be available over WSS.init @ VM5902:215
> VM5902:215 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.init @ chrome-extension://bjnooaekianmbfmjbfgocckmdlcbhcef/script.js:18

错误二（红叉-严重）：

> VM5902:215 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.init @ chrome-extension://bjnooaekianmbfmjbfgocckmdlcbhcef/script.js:18
> VM5941 ?sid=:1 Mixed Content: The page at 'https://c91.yunpan.360.cn/my/?sid=#%2F%E5%B8%B8%E7%94%A8%E7%B4%A0%E6%9D%90%2FEARTHRIVERlogo%2F' was loaded over HTTPS, but requested an insecure image 'http://fe.alarm.yunpan.360.cn/s.gif?msg=Uncaught%20SecurityError%3A%20Faile…0a%20page%20loaded%20over%20HTTPS.&u=&ln=215&cn=37&p=cloud&t=1466573760030'. This content should also be served over HTTPS.

错误三（叹号）：

> Mixed Content: The page at 'https://c91.yunpan.360.cn/my/?sid=#%2F%E5%B8%B8%E7%94%A8%E7%B4%A0%E6%9D%90%2FEARTHRIVERlogo%2F' was loaded over HTTPS, but requested an insecure image 'http://fe.alarm.yunpan.360.cn/s.gif?msg=Uncaught%20SecurityError%3A%20Faile…0a%20page%20loaded%20over%20HTTPS.&u=&ln=215&cn=37&p=cloud&t=1466573760030'. This content should also be served over HTTPS.

看不懂，请高手指点

**Comment by Kumhy** [comment]
等完成手上这个项目就更新一下吧，被禁用了
