### ISSUE TITLE
已失效求更新

### ISSUE THREAD

**Issue by albatr0n** [Kumhy/360Exporter#2]
点击“RPC设置”后无弹出设置窗，目测已经失效，求更新

**Comment by yimingamei** [comment]
同上，点击"RPC"不弹出设置窗，

**Comment by imoldchen** [comment]
看来我来迟了一步，希望作者能继续更新。

**Comment by xf1** [comment]
不懂js,只是设置界面出不来，可以到87行填上自己正确的地址。

**Comment by Kumhy** [comment]
最近一段时间一直在忙公司其他项目，现在闲下来了准备更新下，下个版本应该就可以。
